DEFINE USER_NAME = &&1
DEFINE TBS_DATA_NAME = '&&USER_NAME._DATA'
DEFINE TBS_IDX_NAME = '&&USER_NAME._IDX'

DROP TABLESPACE &&TBS_DATA_NAME
	INCLUDING CONTENTS AND DATAFILES
	CASCADE CONSTRAINTS;
	
DROP TABLESPACE &&TBS_IDX_NAME
	INCLUDING CONTENTS AND DATAFILES
	CASCADE CONSTRAINTS;
	
UNDEFINE TBS_DATA_NAME
UNDEFINE TBS_IDX_NAME