SET TIME ON
SET TIMING ON
SPOOL DROP_SCHEMA.LOG

DEFINE USER_NAME = &&1

SET SERVEROUTPUT ON

PROMPT 'USERNAME: &&USER_NAME'
PROMPT 'EXECUTING drop_user.sql'

@drop_user &&USER_NAME

PROMPT 'USER &&USER_NAME DROPPED SUCCESFULLY'

PROMPT 'EXECUTING drop_tablespace.sql'

@drop_tablespace &&USER_NAME

PROMPT 'TABLESPACE &&USER_NAME._DATA DROPPED SUCCESFULLY'

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME

SPOOL OFF