SET TIME ON
SET TIMING ON
SPOOL DROP_SCHEMA.LOG

DEFINE USER_NAME = &&1

SET SERVEROUTPUT ON

PROMPT USERNAME: &&USERNAME
PROMPT EXECUTING drop_user.sql

@drop_user.sql &&USER_NAME

PROMPT USER &&USER_NAME DROPPED SUCCESFULLY

PROMPT EXECUTING drop_tablespace.sql

@drop_tablespace.sql &&USER_NAME

PROMPT TABLESPACE &&USERNAME._DATA DROPPED SUCCESFULLY

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME

SPOOL OFF