DEFINE VIEW_NAME = &&1

CREATE VIEW &&VIEW_NAME AS 
SELECT 
	SEASONS.SEASON_YEAR AS CHAMPIONSHIP
	LEAGUES.NAME AS LEAGUE
	TEAMS.YEAR_OF_FOUND AS YEAR_OF_FOUND
	TEAMS.NAME AS TEAM_NAME
	COACHES.NAME AS COACH_NAME
	EVENTS.EVENT AS EVENT
	EVENTS.EVENT_TIME AS EVENT_TIME
	MATCHES.DATE_OF_MATCH AS DATE_OF_MATCH
	MATCHES.AVG_PRICE AS AVERAGE_PRICE
	MATCHES.TICKETS_SOLD AS TICKETS_SOLD
	STADIUMS.CITY AS LOCATION
	STADIUMS.CAPACITY AS CAPACITY
	STADIUMS.NAME AS VENUE
	PLAYERS.NAME AS PLAYER_NAME
	PLAYERS.TEAM_NAME AS TEAM_NAME
	PLAYERS.POSITION AS POSITION