DEFINE USER_NAME = &&1
DEFINE DATA_TBS_NAME = '&&USER_NAME._DATA'

CREATE TABLE PLAYER_STATISTICS (
	STATISTIC_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	PLAYER_ID NUMBER,
	SEASON_ID NUMBER,
	GOALS_SCORED NUMBER NOT NULL,
	CONSTRAINTS PLAYER_STATISTICS_PK PRIMARY KEY STATISTIC_ID
) TABLESPACE &&DATA_TBS_NAME;
