CREATE TABLE COACHES (
	COACH_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	NAME VARCHAR2(100),
	BIRTHDAY DATE,
	TEAM_ID NUMBER,
	COACH_RANK VARCHAR2(100),
	SEASON_ID NUMBER,
	CONSTRAINTS COACH_ID_PK PRIMARY KEY (COACH_ID)
);