CREATE TABLE SQUAD (
	SQUAD_ID NUMBER,
	PLAYER_ID NUMBER NOT NULL,
	TEAM_ID NUMBER NOT NULL,
	MEMBERS_NUMBER NUMBER NOT NULL,
	MATCH_ID NUMBER NOT NULL,
	CONSTRAINTS SQUAD_ID_PK PRIMARY KEY (SQUAD_ID)
);