DEFINE USER_NAME = &&1
DEFINE DATA_TBS_NAME = '&&USER_NAME._DATA'

CREATE TABLE MATCHES (
	MATCHES_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	SEASON_ID NUMBER,
	HOME_TEAM_ID NUMBER,
	VISITOR_TEAM_ID NUMBER,
	DATE_OF_MATCH DATE,
	AVG_PRICE DECIMAL,
	TICKETS_SOLD NUMBER,
	CONSTRAINTS MATCHES_ID_PK PRIMARY KEY MATCHES_ID
) TABLESPACE &&DATA_TBS_NAME;