DEFINE USER_NAME = &&1
DEFINE DATA_TBS_NAME = '&&USER_NAME._DATA'

CREATE TABLE TEAMS (
	TEAM_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	NAME VARCHAR2(100),
	LEAGUE_ID NUMBER,
	YEAR_OF_FOUNDATION NUMBER,
	CONSTRAINTS TEAM_ID_PK PRIMARY KEY TEAM_ID
) TABLESPACE &&DATA_TBS_NAME;