DEFINE USER_NAME = &&1
DEFINE INDEX_TBS_NAME = '&&USER_NAME._IDX'

ALTER TABLE PLAYER_STATISTICS ADD CONSTRAINT PLAYER_STATISTICS_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE SET NULL;
CREATE INDEX PLAYER_STATISTICS_SEASON_ID_FK_IDX ON PLAYER_STATISTICS(SEASON_ID) TABLESPACE &&INDEX_TBS_NAME	

ALTER TABLE PLAYER_STATISTICS ADD CONSTRAINT PLAYER_ID_FK FOREIGN KEY(PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID) ON DELETE SET NULL;
CREATE INDEX PLAYER_ID_FK_IDX ON PLAYER_STATISTICS (PLAYER_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE TEAM_STATISTICS ADD CONSTRAINT TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE SET NULL;
CREATE INDEX TEAM_ID_FK_IDX ON TEAM_STATISTICS (TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE TEAM_STATISTICS ADD CONSTRAINT SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE SET NULL;
CREATE INDEX SEASON_ID_FK_IDX ON TEAM_STATISTICS (SEASON_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE STADIUMS ADD CONSTRAINT STADIUMS_TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE SET NULL;
CREATE INDEX STADIUMS_TEAM_ID_FK_IDX ON STADIUMS (TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE TEAMS ADD CONSTRAINT TEAMS_LEAGUE_ID_FK FOREIGN KEY(LEAGUE_ID) REFERENCES LEAGUES(LEAGUE_ID) ON DELETE SET NULL;
CREATE INDEX TEAMS_LEAGUE_ID_FK_IDX ON TEAMS (LEAGUE_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE TRANSFERS ADD CONSTRAINT TRANSFERS_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE SET NULL;
CREATE INDEX TRANSFERS_SEASON_ID_FK_IDX ON TRANSFERS (SEASON_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE TRANSFERS ADD CONSTRAINT TRANSFERS_PLAYER_ID_FK FOREIGN KEY(PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID) ON DELETE SET NULL;
CREATE INDEX TRANSFERS_PLAYER_ID_FK_IDX ON TRANSFERS (PLAYER_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE TRANSFERS ADD CONSTRAINT TRANSFERS_OLD_TEAM_ID_FK FOREIGN KEY(OLD_TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE SET NULL;
CREATE INDEX TRANSFERS_OLD_TEAM_ID_FK_IDX ON TRANSFERS (OLD_TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE TRANSFERS ADD CONSTRAINT TRANSFERS_NEW_TEAM_ID_FK FOREIGN KEY(NEW_TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE SET NULL;
CREATE INDEX TRANSFERS_NEW_TEAM_ID_FK_IDX ON TRANSFERS (NEW_TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE SQUAD ADD CONSTRAINT SQUAD_SQUAD_ID_FK FOREIGN KEY(SQUAD_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE SET NULL;
CREATE INDEX SQUAD_SQUAD_ID_FK_IDX ON SQUAD (SQUAD_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE SQUAD ADD CONSTRAINT SQUAD_PLAYER_ID_FK FOREIGN KEY(PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID) ON DELETE SET NULL;
CREATE INDEX SQUAD_PLAYER_ID_FK_IDX ON SQUAD (PLAYER_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE SQUAD ADD CONSTRAINT SQUAD_TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE SET NULL;
CREATE INDEX SQUAD_TEAM_ID_FK_IDX ON SQUAD (TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE SQUAD ADD CONSTRAINT SQUAD_MATCH_ID_FK FOREIGN KEY(MATCH_ID) REFERENCES MATCHES(MATCH_ID) ON DELETE SET NULL;
CREATE INDEX SQUAD_MATCH_ID_FK_IDX ON SQUAD (MATCH_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE COACHING ADD CONSTRAINT COACHING_TEAM_ID_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE SET NULL;
CREATE INDEX COACHING_TEAM_ID_FK_IDX ON COACHING (TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE COACHING ADD CONSTRAINT COACHING_COACH_ID_FK FOREIGN KEY(COACH_ID) REFERENCES COACHES(COACH_ID) ON DELETE SET NULL;
CREATE INDEX COACHING_COACH_ID_FK_IDX ON COACHING (COACH_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE COACHING ADD CONSTRAINT COACHING_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE SET NULL;
CREATE INDEX COACHING_SEASON_ID_FK_IDX ON COACHING (SEASON_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE MATCHES ADD CONSTRAINT MATCHES_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE SET NULL;
CREATE INDEX MATCHES_SEASON_ID_FK_IDX ON MATCHES(SEASON_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE MATCHES ADD CONSTRAINT MATCHES_HOME_TEAM_ID_FK FOREIGN KEY(HOME_TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE SET NULL;
CREATE INDEX MATCHES_HOME_TEAM_ID_FK_IDX ON MATCHES (HOME_TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE MATCHES ADD CONSTRAINT MATCHES_VISITOR_TEAM_ID_FK FOREIGN KEY(VISITOR_TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE SET NULL;
CREATE INDEX MATCHES_VISITOR_TEAM_ID_FK_IDX ON MATCHES (VISITOR_TEAM_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE EVENTS ADD CONSTRAINT EVENTS_SEASON_ID_FK FOREIGN KEY(SEASON_ID) REFERENCES SEASONS(SEASON_ID) ON DELETE SET NULL;
CREATE INDEX EVENTS_SEASON_ID_FK_IDX ON EVENTS (SEASON_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE EVENTS ADD CONSTRAINT EVENTS_MATCH_ID_FK FOREIGN KEY(MATCH_ID) REFERENCES MATCHES(MATCH_ID) ON DELETE SET NULL;
CREATE INDEX EVENTS_MATCH_ID_FK_IDX ON EVENTS(MATCH_ID) TABLESPACE &&INDEX_TBS_NAME

ALTER TABLE EVENTS ADD CONSTRAINT EVENTS_PLAYER_ID_FK FOREIGN KEY(PLAYER_ID) REFERENCES PLAYERS(PLAYER_ID) ON DELETE SET NULL;
CREATE INDEX EVENTS_PLAYER_ID_FK_IDX ON EVENTS(PLAYER_ID) TABLESPACE &&INDEX_TBS_NAME

UNDEFINE USER_NAME
UNDEFINE INDEX_TBS_NAME