DEFINE USER_NAME = &&1
DEFINE DATA_TBS_NAME = '&&USER_NAME._DATA'

CREATE TABLE SEASONS (
	SEASON_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	SEASON_YEAR NUMBER,
	CONSTRAINTS SEASON_ID_PK PRIMARY KEY SEASON_ID
) TABLESPACE &&DATA_TBS_NAME;