DEFINE USER_NAME = &&1
DEFINE DATA_TBS_NAME = '&&USER_NAME._DATA'

CREATE TABLE STADIUMS (
	STADIUM_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	NAME VARCHAR2(100),
	CITY VARCHAR2(100),
	CAPACITY NUMBER,
	TEAM_ID NUMBER,
	CONSTRAINTS STADIUM_ID_PK PRIMARY KEY STADIUM_ID
) TABLESPACE &&DATA_TBS_NAME;