CREATE TABLE TEAM_STATISTICS (
	STATISTIC_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL,
	TOUCHDOWNS NUMBER NOT NULL,
	RUSHINGYARDS NUMBER NOT NULL,
	TEAM_ID NUMBER NOT NULL,
	SEASON_ID NUMBER NOT NULL,
	CONSTRAINTS STATISTIC_ID_PK PRIMARY KEY (STATISTIC_ID)
);