SET TIME ON
SET TIMING ON
SPOOL UPGRADE_SCHEMA.LOG

PROMPT Enter username
DEFINE USER_NAME = &&1
PROMPT Enter password
DEFINE SCHEMA_PASSWORD = &&2


SET SERVEROUTPUT ON
PROMPT Username to upgrade: &&USER_NAME
PROMPT Password to upgrade: &&SCHEMA_PASSWORD

connect &&USER_NAME/&&SCHEMA_PASSWORD

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
UNDEFINE SCHEMA_PASSWORD

SPOOL OFF