DEFINE USER_NAME = &&1
DEFINE TBS_LOCATION = &&2
DEFINE TBS_TYPE = &&3
DEFINE DATA_TBS_NAME = '&&USER_NAME._&&TBS_TYPE'
DEFINE DATA_FILENAME = '&&TBS_LOCATION&&DATA_TBS_NAME..dbf'
DEFINE INDEX_NAME = '&&USERNAME._IDX'
DEFINE INDEX_FILENAME = '&&FILE_PATH.&&INDEX_NAME..dbf'

CREATE TABLESPACE &&DATA_TBS_NAME
    DATAFILE '&&DATA_FILENAME' SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE 10G;
	
CREATE TABLESPACE &&INDEX_NAME
    DATAFILE '&&INDEX_FILENAME' SIZE 10M AUTOEXTEND ON NEXT 100M MAXSIZE 10G;	

UNDEFINE USER_NAME
UNDEFINE TBS_LOCATION
UNDEFINE TBS_TYPE
UNDEFINE DATA_TBS_NAME
UNDEFINE DATA_FILENAME
UNDEFINE INDEX_NAME
UNDEFINE INDEX_FILENAME